SET SCHEMA FN71923;

-- VIEWS
CREATE VIEW ATTENDEDCOURSES AS
SELECT S.NAME AS STUDENTNAME, C.NAME AS COURSENAME
FROM STUDENTS S, ATTENDS A, COURSES C
WHERE S.EGN = A.STUDENTEGN AND A.COURSEYEAR = C.YEAR AND A.COURSENUMBER = C.COURSENUMBER;

SELECT * FROM ATTENDEDCOURSES;

CREATE VIEW MENTOROFDEPARTMENTS AS
SELECT D.NAME AS DEPARTMENT, T.NAME AS TEACHER
FROM DEPARTMENTS D, TEACHER T
WHERE D.TEACHEREGN = T.TEACHEREGN;

SELECT * FROM MENTOROFDEPARTMENTS;