SET SCHEMA FN71923;

--CREATING TABLES

--Table with faculty
CREATE TABLE FACULTIES
(
    facultyName VARCHAR(30) NOT NULL,
    facultyID CHAR(2) NOT NULL PRIMARY KEY,
    faddress VARCHAR(100)
);

--Table with department
CREATE TABLE DEPARTMENTS
(
    name VARCHAR(30) NOT NULL PRIMARY KEY,
    facultyID CHAR(2) NOT NULL,
    teacherEGN CHAR(10)
);

--Table with degree
CREATE TABLE DEGREE
(
    abbreviation VARCHAR(5) NOT NULL PRIMARY KEY ,
    degreeName VARCHAR(30) NOT NULL
);

--Table with teacher
CREATE TABLE TEACHER
(
    name VARCHAR(50) NOT NULL,
    teacherEGN CHAR(10) NOT NULL PRIMARY KEY,
    scientificTitle VARCHAR(30),
    departmentName VARCHAR(30) NOT NULL
);

--Table with student
CREATE TABLE STUDENTS
(
    name VARCHAR(50) NOT NULL,
    EGN CHAR(10) NOT NULL PRIMARY KEY,
    facultyNumber CHAR(5) NOT NULL,
    major VARCHAR(30) NOT NULL,
    yearOfStudying INTEGER,
    facultyID CHAR(2) NOT NULL,
    mentor CHAR(10) NOT NULL
);

--Table with courses
CREATE TABLE COURSES
(
    name VARCHAR(50) NOT NULL,
    courseNumber INTEGER NOT NULL,
    year INTEGER NOT NULL,
    type VARCHAR(30),
    description VARCHAR(100),
    teacherEGN CHAR(10) NOT NULL,
    PRIMARY KEY (courseNumber, year)
);

--Table with attends
CREATE TABLE ATTENDS
(
    studentEGN CHAR(10) NOT NULL,
    courseNumber INTEGER NOT NULL,
    courseYear INTEGER NOT NULL,
    PRIMARY KEY (studentEGN, courseNumber, courseYear)
);

--Table with has degree
CREATE TABLE HASDEGREE
(
    teacherEGN CHAR(10) NOT NULL,
    abbreviation VARCHAR(5) NOT NULL,
    PRIMARY KEY (teacherEGN, abbreviation)
);

-- FOREIGN KEY CONSTRAINTS

ALTER TABLE STUDENTS
ADD CONSTRAINT FK_STUDENTS_FACULTIES
FOREIGN KEY (facultyID) REFERENCES FACULTIES(facultyID);

ALTER TABLE STUDENTS
ADD CONSTRAINT FK_STUDENTS_TEACHERS
FOREIGN KEY (mentor) REFERENCES TEACHER(teacherEGN);

ALTER TABLE COURSES
ADD CONSTRAINT FK_COURSES_TEACHERS
FOREIGN KEY (teacherEGN) REFERENCES TEACHER(teacherEGN);

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT FK_DEPARTMENTS_FACULTIES
FOREIGN KEY (facultyID) REFERENCES FACULTIES(facultyID);

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT FK_DEPARTMENTS_TEACHERS
FOREIGN KEY (teacherEGN) REFERENCES TEACHER(teacherEGN);

ALTER TABLE ATTENDS
ADD CONSTRAINT FK_ATTENDS_STUDENTS
FOREIGN KEY (studentEGN) REFERENCES STUDENTS(EGN);

ALTER TABLE ATTENDS
ADD CONSTRAINT FK_ATTENDS_COURSES
FOREIGN KEY (courseNumber, courseYear) REFERENCES COURSES(courseNumber, year);

ALTER TABLE HASDEGREE
ADD CONSTRAINT FK_HASDEGREE_TEACHERS
FOREIGN KEY (teacherEGN) REFERENCES TEACHER(teacherEGN);

ALTER TABLE HASDEGREE
ADD CONSTRAINT FK_HASDEGREE_DEGREES
FOREIGN KEY (abbreviation) REFERENCES DEGREE(abbreviation);

-- CHECKS

ALTER TABLE STUDENTS
ADD CONSTRAINT CHECK_YEAR
CHECK (yearOfStudying IN (1,2,3,4) OR yearOfStudying IS NULL);

ALTER TABLE STUDENTS
ADD CONSTRAINT CHECK_FN
CHECK (facultyNumber > 0);